src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api.views import BookViewSet, BorrowedBooksView

schema_view = get_schema_view(
    openapi.Info(
        title="Library API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@library.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register(r"books", BookViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("my-books/", BorrowedBooksView.as_view(), name="my-books"),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("library_app.urls")),
    path("api/", include("api.urls")),
    path("users/", include("users.urls")),
]

src/library_app/urls.py
from django.urls import path

from . import views

app_name = "library_app"


urlpatterns = [
    path("", views.index, name="index"),
    path("my_books/", views.my_books, name="my_books"),
    path("borrow/<int:book_id>/", views.borrow_book, name="borrow_book"),
    path("return/<int:book_id>/", views.return_book, name="return_book"),
]

src/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(template_name="users/logged_out.html"), name="logout"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
]

src/library_app/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

User = get_user_model()


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class BorrowRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="borrow_record")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="borrow_record")
    borrowed_at = models.DateTimeField(auto_now_add=True)
    returned_at = models.DateTimeField(null=True, blank=True)

    def days_borrowed(self):
        if self.returned_at:
            return (self.returned_at - self.borrowed_at).days
        return (timezone.now() - self.borrowed_at).days

src/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    LIBRARIAN = "librarian"
    READER = "reader"

    ROLES = (
        (LIBRARIAN, "Библиотекарь"),
        (READER, "Читатель"),
    )
    role = models.CharField(verbose_name="Роль", default="reader", choices=ROLES, max_length=15)
    tab_number = models.CharField(max_length=50, null=True, blank=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    address = models.TextField(null=True, blank=True)

src/library_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()


class LibrarianSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "tab_number")


class ReaderSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "first_name", "last_name", "address")


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password")

src/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username",)

src/api/views.py
from django.utils import timezone
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import BookSerializer, BorrowSerializer
from library_app.models import Book, BorrowRecord


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    permission_classes = [IsAuthenticated]

    @action(detail=True, methods=["post"])
    def borrow(self, request, pk=None):
        book = self.get_object()
        if not BorrowRecord.objects.filter(book=book, user=request.user, returned_at__isnull=True).exists():
            BorrowRecord.objects.create(book=book, user=request.user)
        return Response({"status": "book borrowed"})

    @action(detail=True, methods=["post"])
    def return_book(self, request, pk=None):
        book = self.get_object()
        borrow_record = BorrowRecord.objects.filter(book=book, user=request.user, returned_at__isnull=True).first()
        if borrow_record:
            borrow_record.returned_at = timezone.now()
            borrow_record.save()
            return Response({"status": "book returned"})
        else:
            return Response({"status": "you did not borrow this book"}, status=status.HTTP_400_BAD_REQUEST)


class BorrowedBooksView(APIView):
    """Список книг на руках"""

    permission_classes = [IsAuthenticated]

    def get(self, request):
        my_books = request.user.borrow_record.all()
        serializer = BorrowSerializer(my_books, many=True)
        return Response(serializer.data)

src/library_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from .models import Book, BorrowRecord
from .utils import paginat

User = get_user_model()


def index(request):
    books = Book.objects.all()
    debtors = BorrowRecord.objects.select_related("user", "book")
    borrow_books = []
    if request.user.is_authenticated:
        borrows = request.user.borrow_record.all()
        for borrow in borrows:
            if not borrow.returned_at:
                borrow_books.append(borrow.book.id)
        page_obj = paginat(request, books)
        context = {"page_obj": page_obj, "borrow_books": borrow_books, "debtors": debtors}
        return render(request, "library/index.html", context)
    return redirect("users:login")


@login_required
def borrow_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if not BorrowRecord.objects.filter(book=book, user=request.user, returned_at__isnull=True).exists():
        BorrowRecord.objects.create(book=book, user=request.user)
    return redirect("library_app:index")


@login_required
def return_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    borrow_record = BorrowRecord.objects.filter(book=book, user=request.user, returned_at__isnull=True).first()
    if borrow_record:
        borrow_record.returned_at = timezone.now()
        borrow_record.save()
    return redirect("library_app:index")


@login_required
def my_books(request):
    borrows = request.user.borrow_record.filter(returned_at__isnull=True).order_by("book__title")
    return render(request, "library/my_books.html", {"borrows": borrows})

src/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("users:login")
    template_name = "users/signup.html"

src/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  {% include 'includes/head.html' %}
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>  
    {% include 'includes/footer.html' %}     
  </body>
</html>

src/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

src/templates/includes/book.html
<article>
  <ul>
    <li>
      Автор: {{ book.author }}
    </li>
    <li>
      Жанр: {{ book.genre }}
    </li>
    <li>
      Название: {{ book.title }}
      <button class="copy-button" data-clipboard-text="{{ book.title }}">
        Копировать
      </button>
    </li>
    {% if user.is_authenticated %}
      {% if book.id in borrow_books %}
        <form method="post" action="{% url 'library_app:return_book' book_id=book.id %}"> 
          {% csrf_token %}
          <button type="submit">Отдать</button>
        </form>
      {% else %}
      <form method="post" action="{% url 'library_app:borrow_book' book_id=book.id %}">
        {% csrf_token %}
          <button type="submit">Взять</button>
        </form>
      {% endif %}
    {% endif %}
  </ul>
</article>


{% block extra_js %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
      const copyButtons = document.querySelectorAll('.copy-button');

      copyButtons.forEach(button => {
          button.addEventListener('click', () => {
              // Создаем временный элемент для копирования текста
              const tempInput = document.createElement('input');
              tempInput.value = button.getAttribute('data-clipboard-text');
              document.body.appendChild(tempInput);

              // Выбираем и копируем текст
              tempInput.select();
              document.execCommand('copy');

              // Удаляем временный элемент
              document.body.removeChild(tempInput);

              // Меняем текст кнопки
              button.textContent = 'Скопировано!';

              // Восстанавливаем текст кнопки через 2 секунды
              setTimeout(() => {
                  button.textContent = 'Копировать';
              }, 2000);
          });
      });
  });
</script>
{% endblock %}

src/templates/includes/debtor.html
<article>
    <ul>
      <li>
        username: {{ debtor.user.username }}
      </li>
      <li>
        Имя: {{ debtor.user.first_name }}
      </li>
      <li>
        Фамилия: {{ debtor.user.last_name }}
      </li>
      <li>
        Дата: {{ debtor.borrowed_at }}
      </li>
      <li>
        Название: {{ debtor.book.title }}
      </li>
      <li>
        Количество дней, сколько книга на руках: {{ debtor.days_borrowed }}
      </li>
    </ul>
  </article>

src/templates/includes/error.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

src/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Take</span>Rubles</p>    
</footer>

src/templates/includes/form.html
{% load user_filters %}
<div class="form-group row my-3 p-3">
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
  </label>
  {{ field|addclass:'form-control' }} 
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
</div>

src/templates/includes/head.html
{% load static %}
<head>    
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>
    {% block title %} Библиотека {% endblock %}
  </title>
</head>

src/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'library_app:index' %}">
        <span style="color:red">Take</span>Rubles
      </a>
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'library_app:my_books' %}active{% endif %}" 
             href="{% url 'library_app:my_books' %}"
          >
            Мои книги
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>      
</header>

src/templates/includes/my_book.html
<article>
  <ul>
    <li>
      Название: {{ book.book.title }}
    </li>
    <li>
      Дата получения: {{ book.borrowed_at }}
    </li>
    <li>
      Количество дней, сколько книга на руках: {{ book.days_borrowed }}
    </li>
  </ul>

</article>

src/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

src/templates/library/index.html
{% extends 'base.html' %}
{% block content %}
  {% if user.is_authenticated and user.role == 'reader' %}
    <h1>Книги</h1>
    {% for book in page_obj %}
      {% include 'includes/book.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% elif user.is_authenticated and user.role == 'librarian' %}
    <h1>Должники</h1>
    {% for debtor in debtors %}
      {% include 'includes/debtor.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endif %}
  {% include 'includes/paginator.html' %}
{% endblock %}

src/templates/library/my_books.html
{% extends 'base.html' %}
{% block content %}     
  <h1>Мои книги</h1>
  {% for book in borrows %}
    {% include 'includes/my_book.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

src/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти
        </div>
        <div class="card-body">
          {% include 'includes/error.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

src/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% include 'includes/error.html' %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                {% include 'includes/form.html' %} 
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}